#!/bin/bash

#SBATCH -o /home/icb/jonas.flor/gastrulation_atlas/scvi/training/bash_messages/outputs_prep_10k
#SBATCH -e /home/icb/jonas.flor/gastrulation_atlas/scvi/training/bash_messages/errors_prep_10k
#SBATCH -J prep_10k
#SBATCH -p cpu_p
#SBATCH --qos=cpu_normal
#SBATCH --mem=150G
#SBATCH -t 15:00:00
#SBATCH --nice=100000


source $HOME/.bashrc

mamba activate scvi
python /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/preprocessing.py 10k_genes

path="$(grep -iE 'killed' /home/icb/jonas.flor/gastrulation_atlas/scvi/training/bash_messages/errors_prep_10k)"
if [ -z "$path" ]
then                    
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_ari_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_ari_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_ASW_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_ASW_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_cLISI_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_cLISI_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_graph_connectivity_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_graph_connectivity_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_hgv_overlap_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_iLISI_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_iLISI_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_iso_labels_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_iso_labels_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_nmi_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_nmi_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_pcr_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_pcr_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_silhouette_batch_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_silhouette_batch_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_silhouette_integrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_silhouette_unintegrated_10k
    sbatch /home/icb/jonas.flor/gastrulation_atlas/scvi/training/model_1M_final/metric_traject_conservation_10k
    echo "Done!"
else
    echo "Error produced"
fi
                        
                        